### PR TITLE
WIP: Upgradeable contracts

### PR DESCRIPTION
**Pull request by benbjohnson**
## Overview

This pull request implements upgradeable contracts for GoChain. It works by implementing several steps:

1. Add `SYSCON` (`0xDF`) EVM opcode to mark a contract as a system contract. This is a no-op opcode that simply acts as a marker to notify the EVM not to charge gas for the contract operation.

2. Delegate & delegate storage contract injection. This works by catching incoming contract creation and building two additional contracts: `Delegator` & `DelegateStorage`.

The `DelegateStorage` contract acts simply as an empty contract that we can invoke another contract from. By using the `delegatecall` opcode we execute the user's original contract but use the `DelegateContract`'s storage. This allows us to change the contract code without losing the storage.

The `Delegator` contract stores the `storage` & `target` contract addresses and invokes the storage on execution. The delegator is required so that no storage in the `storage` contract is used to store the target address.

### TODO

- [ ] Prevent outside contracts from using the `SYSCON` EVM opcode.
- [x] Fix target contract injection.

### CODE REVIEW

**Comment by treeder** [comment]
Looks good! re: https://github.com/gochain-io/gochain/pull/331

Any docs on how to test it?

**Comment by jmank88** [comment]
Is `pausing` currently supported? (Perhaps implicitly, by setting an empty address or something?)

**Comment by benbjohnson** [comment]
I finally got the `delegatecall()` & fallback function to correctly pass back the original return values from the delegated contract invocation. It seems like it should have been easier but it requires going down to the assembly level and manipulating the `RETURNDATASIZE` & `RETURNDATACOPY` opcodes.

Here's the `delegatecall()` implementation: https://github.com/gochain-io/gochain/blob/1341162e90fd00846a93eb2e45e106ca13a803f9/contracts/delegator/delegator.sol#L6-L15

Here's the similar implementation for the fallthrough function: https://github.com/gochain-io/gochain/blob/1341162e90fd00846a93eb2e45e106ca13a803f9/contracts/delegator/delegator.sol#L35-L50

**Comment by treeder** [comment]
I'm making a hello world contract for web3 that we can reuse for this, so let's wait until that's in.

**Comment by treeder** [comment]
Can use this one as an example: https://github.com/gochain-io/web3/blob/master/contracts/README.md

Just add in a couple steps to change contract and redeploy it.

**Pull request closed without merging**
